### ISSUE TITLE
question about configuration

### ISSUE THREAD

**Issue by e-v-medvedev** [acelaya/ZF2-AcMailer#120]
Explane the purpose of "console/router/routes" section please.

**Comment by acelaya** [comment]
The v5 of this module includes a console command that is used to migrate configuration from v4

**Comment by e-v-medvedev** [comment]
:-) I`m trying to connect module with this https://github.com/BitWeb/zf2-cron-module. And when i run cron command in cli, i see AcMailer log "index.php acmailer parse-config [--configKey=] [--format=(php|xml|ini|json)] [--outputFile=] ..."
Is any way to switch it off without editing source code?

**Comment by acelaya** [comment]
That's the console usage specification, and I don't think it can be disabled, but what's the problem that you see that anyway? If you don't want to save the output of the command, redirect it to /dev/null.
You are going to have this same problem with any module that comes with console support.

However, maybe you can try extending the Module class into a new ZF2 module, and registering that module instead of AcMailer. Then override the getConsoleUsage method so that it returns an empty array. (I'm not sure if this works because I haven't tested it)
